# Generated by Django 6.1 on 2026-08-06 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('related_entity_type', models.CharField(blank=True, max_length=50)),
                ('related_entity_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('expired', 'Expired'), ('actioned', 'Actioned')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('repeat_interval_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_app.business')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
