# Generated by Django 6.0.8 on 2026-08-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='classification',
            field=models.CharField(blank=True, choices=[('matched', 'Matched / left in business'), ('shortfall', 'Genuine shortfall')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='type',
            field=models.CharField(choices=[('shortfall', 'Shortfall'), ('free_giveaway', 'Free giveaway'), ('non_business_transaction', 'Non-business transaction'), ('salary_payment', 'Salary payment')], max_length=30),
        ),
    ]
