# Generated by Django 6.0.8 on 2026-08-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passcode_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
