# Generated by Django 6.0.8 on 2026-08-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
