# Generated by Django 6.0.8 on 2026-08-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_alter_item_buying_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcollection',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched'), ('partial_left_in_business', 'Partial — left in business'), ('shortfall_pending', 'Shortfall pending'), ('shortfall_approved', 'Shortfall approved')], default='matched', max_length=25),
        ),
    ]
