# Generated by Django 6.0.8 on 2026-08-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_alter_cashcollection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionperiod',
            name='module',
            field=models.CharField(default='bar', max_length=10),
        ),
    ]
