# Generated by Django 6.0.8 on 2026-08-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0005_salarypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcollection',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched'), ('partial_left_in_business', 'Partial — left in business'), ('shortfall_pending', 'Shortfall pending'), ('shortfall_approved', 'Shortfall approved'), ('overage_pending', 'Overage pending'), ('overage_approved', 'Overage approved')], default='matched', max_length=25),
        ),
    ]
