# Generated by Django 6.0.8 on 2026-08-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0006_alter_cashcollection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='freegiveaway',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
