# Generated by Django 6.0.8 on 2026-08-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0007_freegiveaway_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionperiod',
            name='carried_forward_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
