# Generated by Django 6.0.8 on 2026-08-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0008_collectionperiod_carried_forward_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcollection',
            name='previous_expected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashcollection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
