# Generated by Django 6.0.8 on 2026-08-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0009_cashcollection_previous_expected_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcollection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=25),
        ),
    ]
