# Generated by Django 6.0.8 on 2026-08-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0010_alter_cashcollection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashcollection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
