# Generated by Django 6.0.8 on 2026-08-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0011_alter_cashcollection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='written_off_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
