# Generated by Django 6.0.8 on 2026-08-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0012_loan_written_off_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='effective_date',
        ),
    ]
