# Generated by Django 6.0.8 on 2026-08-12 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0013_remove_salary_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
