# Generated by Django 6.0.8 on 2026-08-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0014_salary_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionperiod',
            name='last_collection_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
