# Generated by Django 6.0.8 on 2026-08-14 17:12

import apps.bar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0015_collectionperiod_last_collection_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='effective_date',
            field=models.DateField(default=apps.bar.models.today_date),
        ),
    ]
