# Generated by Django 6.0.8 on 2026-08-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0016_alter_salary_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonbusinesstransaction',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('salary', 'Salary')], default='general', max_length=20),
        ),
    ]
