// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4-iUuSy4Q13BhjvTWsU4yHtVGKGUGdvg',
    appId: '1:903008382592:web:6343cedb60bb0ec50e8065',
    messagingSenderId: '903008382592',
    projectId: 'business-manager-a29d5',
    authDomain: 'business-manager-a29d5.firebaseapp.com',
    storageBucket: 'business-manager-a29d5.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_TxPpqpa9maeyVgjEvgakHStCdKOYq60',
    appId: '1:903008382592:ios:74cf9c1df29bb5930e8065',
    messagingSenderId: '903008382592',
    projectId: 'business-manager-a29d5',
    storageBucket: 'business-manager-a29d5.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4-iUuSy4Q13BhjvTWsU4yHtVGKGUGdvg',
    appId: '1:903008382592:web:5e3155a7d87f8fe50e8065',
    messagingSenderId: '903008382592',
    projectId: 'business-manager-a29d5',
    authDomain: 'business-manager-a29d5.firebaseapp.com',
    storageBucket: 'business-manager-a29d5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_TxPpqpa9maeyVgjEvgakHStCdKOYq60',
    appId: '1:903008382592:ios:74cf9c1df29bb5930e8065',
    messagingSenderId: '903008382592',
    projectId: 'business-manager-a29d5',
    storageBucket: 'business-manager-a29d5.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMLDzkfd6wqFB0Xzngz10ppANKY9qdGb0',
    appId: '1:903008382592:android:5948a203658f2a010e8065',
    messagingSenderId: '903008382592',
    projectId: 'business-manager-a29d5',
    storageBucket: 'business-manager-a29d5.firebasestorage.app',
  );
}
